stages:
  - build
  - deploy

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

build:
  stage: build
  image: docker:19.03
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - ./build.sh
  artifacts:
    paths:
    - _site
  only:
    - source
  cache:
    paths:
      - vendor/

deploy_prod:
  stage: deploy
  image: node:12.13.0-alpine
  before_script:
    - npm i -g firebase-tools
  script:
    - firebase deploy -f --token $FIREBASE_DEPLOY_KEY
  dependencies:
    - build
  only:
    - source
