language: ruby
dist: trusty
rvm: 2.2

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: gh-pages

before_script:
 - chmod +x ./cibuild

script: ./cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: true
