theme: beautiful-jekyll-theme

# Site wide configuration

title: Samsul Ma'arif
author: Samsul Ma'arif
locale: id_ID
description: Catatan kecil pengguna Linux.
keywords: sysadmin,docker,system administrator,sysadmin malang,jasa sysadmin,jasa devops
search: true
timezone: Asia/Jakarta
url: https://blog.samsul.web.id

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Tentang: "http://www.samsul.web.id"
  Komunitas:
    - KLiM: "https://www.klim.or.id"
    - openSUSE: "http://opensuse.id"
    - GNOME: "http://gnome.id"
    - Daunsalam: "http://daunsalam.samsul.web.id/"
  Wiki: "http://wiki.samsul.web.id"
  Training: "https://nacita.id"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.png"
round-avatar: true
favicon: "/img/favicon.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
social-network-links:
  rss: true
  name: Samsul Ma'arif
  email: "hay@samsul.web.id"
  facebook: samsul.web.id
  github: samsulmaarif
  twitter: samsulmaarif_
#  reddit: yourname    # eg. daattali
#  google-plus: +yourname   # eg. +DeanAttali or 109424658772469020925
  linkedin: samsulmaarif  # eg. daattali
#  xing: yourname      # eg. daattali
#  stackoverflow: yourlink  # eg. "3943160/daattali"
#  snapchat: yourname  # eg. daattali
  instagram: samsul.web.id
#  youtube: yourlink   # eg. user/daattali or channel/daattali
#  spotify: yourname   # eg. daattali
#  telephone:


# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "www.samsul.web.id"

# --- Misc --- #
# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "blogsamsul"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-130238985-1"

# Google Tag Manager ID
gtm: "G-N5HRM4RFRS"

# Facebook App ID
fb_app_id: "642615472602024"

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# --- Colours / background image --- #
mobile-theme-col: "#0085A1"

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Asia/Jakarta"
markdown: kramdown
highlighter: rouge
permalink:   /:year/:month/:title.html
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      footer-extra: mdgallery.html
      css: "assets/css/site.css"
      # js: "assets/js/md-gallery.js"
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true
      footer-extra: mdgallery.html


link-tags: false
feed_show_excerpt: true

exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
  - blog-05-27-2017.xml
  - docker-compose.yml
  - .travis.yml
  - vendor
  - .firebase
  - .firebaserc
  - firebase.json
  - firebase-debug.log
  - build.sh
