version: '3'
services:
  site:
    command: /bin/bash -c "bundle install && jekyll serve --watch --force_polling --verbose --incremental"
    image: jekyll/jekyll:3.8
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - 4002:4000
    environment:
      JEKYLL_ENV: local
